language: node_js
sudo: false
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
    - /home/travis/.npm-dep
node_js:
  - "4.1"
after_success:
  - npm run semantic-release
